### ISSUE TITLE
inheritance support

### ISSUE THREAD

**Issue by frickt** [dart-lang/json_serializable#145]
Is inheritance supported? I've tried the following example but got an exception, is there something i miss?: 

```
@JsonSerializable()
abstract class Base extends Object with _$BaseSerializerMixin {
  Base(this.value);

  num value;

  factory Base.fromJson(Map<String, dynamic> json) => _$BaseFromJson(json);
}

@JsonSerializable()
class Sub extends Base with _$SubSerializerMixin {
  Sub(num value, this.subVal): super(value);

  num subVal;

  factory Sub.fromJson(Map<String, dynamic> json) => _$SubFromJson(json);
}
```

exception thrown:

> Unsupported operation: Cannot populate the required constructor argument: value.

**Comment by kevmoo** [comment]
Remove the `@JsonSerialiazble` annotation on `Base`.

**Comment by kevmoo** [comment]
I just did this w/ the example and it worked great

```dart

abstract class ItemCore {
  final int price;

  ItemCore(this.price);
}

@JsonSerializable()
class Item extends ItemCore with _$ItemSerializerMixin {
  int count;
  int itemNumber;
  bool isRushed;

  Item(int price) : super(price);

  factory Item.fromJson(Map<String, dynamic> json) => _$ItemFromJson(json);
}
```

Does it work for you?

**Comment by kevmoo** [comment]
run 'pub upgrade' – which version of json_serializable are you using?

**Comment by frickt** [comment]
Your example has the same issue:
> Unsupported operation: Cannot populate the required constructor argument: price.

Maybe, the problem is flutter here, i'm using the configuration described here: https://flutter.io/json/

I did
```
flutter upgrade
flutter pub upgrade
```
both had no impact.
my yaml file looks like that: 

```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  shared_preferences: 0.4.1
  font_awesome_flutter: 6.0.0
  json_annotation: ^0.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^0.7.6
  json_serializable: ^0.3.2

```
