### ISSUE TITLE
NoSuchMethodError: No static getter 'terminal' declared in class 'StdioType'.

### ISSUE THREAD

**Issue by EdHubbell** [dart-lang/json_serializable#164]
This error appeared for me when running `flutter packages pub run build_runner build`.
This was with my pubspec.yaml set to 
````
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.8.0
  json_serializable: ^0.5.2
````

According to https://github.com/dart-lang/build/issues/1463, pinning build_runner to 0.8.8 is the fix. 

So use 
````dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.8.8
  json_serializable: ^0.5.2
````
