### ISSUE TITLE
generated code fails static analysis strong type checking

### ISSUE THREAD

**Issue by diablodale** [dart-lang/json_serializable#247]
The code generated does not have types on several parameters. It also implicitly casts to a more specific type. This is loosely typed and fails static analysis w/ strong checking.

The generated code functions. Rather, these errors appear in IDEs and other tools that digest code analysis. So the fix is to provide a way to understand or rid the errors.

### Setup

* json_serializable 0.5.8
* flutter 0.5.1
* analysis_options.yaml with the following:
```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

### Repo steps

1. Write a flutter app
2. Create object `Item` which has some simple fields like a `String` and `int`.
3. Create object `MyGroup` which has a field `List<Item> myItems;` and `Set<Item> myItemSet;`
4. Annotate these objects and use common json_serializable procedure for them.
5. `flutter packages pub run build_runner build`
6. View the code in your IDE.

### Result

Errors in your IDE for that generated code. You can see in the dart files and the missing param types.
In the below generated code, the `e` has no type declared. Then, the Iterable created from the Json is being assigned to a Set.

```dart
MyGroup _$MyGroupFromJson(Map<String, dynamic> json) {
  return new MyGroup(
      myItems: (json['myItems'] as List)
          ?.map((e) => e == null
              ? null
              : new Item.fromJson(e as Map<String, dynamic>))
          ?.toList(),
      myItemSet: (json['myItemSet'] as List)?.map((e) =>
          e == null ? null : new Item.fromJson(e as Map<String, dynamic>)),
  );
}


```

### Possible Quick Fixes

* Setup `analysis_options.yaml` to ignore the generated files with a glob that matches only the generated files with loose types.

or

* Put `dynamic` before the two scenarios having the `e` parameter.
* Put the type after the `.map`, for example `?.map<Item>((`
* Put `new Set<Item>.from(...)` around the whole Iterable

**Comment by kevmoo** [comment]
I support `implicit-casts: false`, but not `implicit-dynamic: false` – the generated code just gets too complex.

Why are you using `implicit-dynamic: false` ?

**Comment by kevmoo** [comment]
See the discussion here https://github.com/dart-lang/json_serializable/pull/73

We are pondering some more strict checks that are less onerous than `implicit-dynamic: false`. We may consider updates once those checks are available.

**Comment by hpoul** [comment]
fwiw, i have made a very simple builder which allows to add `// ignore_for_file: strong_mode_implicit_dynamic_parameter` to the generated part files, which silences those errors: https://github.com/hpoul/builder_static_text has anyone found a better/simpler workaround? (since for me analyser exclude property did not work)

**Comment by kevmoo** [comment]
> fwiw, i have made a very simple builder which allows to add `// ignore_for_file: strong_mode_implicit_dynamic_parameter` to the generated part files, which silences those errors: https://github.com/hpoul/builder_static_text has anyone found a better/simpler workaround? (since for me analyser exclude property did not work)

Related to https://github.com/dart-lang/source_gen/issues/370

We need to get this back!

**Comment by bsutton** [comment]
Can I add my voice to getting a resolution for this.
We use strong mode on all of projects as it reduces runtime errors.
```
analyzer:
 strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

**Comment by fzyzcjy** [comment]
+1 We also face this problem. Strong mode is quite helpful as it reduces bugs!

**Comment by fzyzcjy** [comment]
In addition, I find the workaround of `strong_mode_implicit_dynamic_parameter` does not work...

For example: After adding it, it still errors!

Is there any updates?

![image](https://user-images.githubusercontent.com/5236035/132127029-3c44f82d-4489-4111-8898-204c5d62c67f.png)

**Comment by kevmoo** [comment]
We're likely not going to change this. It adds A LOT of extra code.

Try this in your `build.yaml` file.

```yaml
# Read about `build.yaml` at https://pub.dev/packages/build_config
# To update generated code, run `pub run build_runner build`
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
          - strong_mode_implicit_dynamic_parameter
```

...or similar for whichever lint/hint you want to ignore
