### ISSUE TITLE
I'm using flutter beta channel, and got error "flutter_driver from sdk is incompatible with json_serializable >=0.5.3".

### ISSUE THREAD

**Issue by jaggerwang** [dart-lang/json_serializable#253]
## Problem

```
[app] flutter packages get
Running "flutter packages get" in app...
Because every version of flutter_driver from sdk depends on analyzer 0.31.2-alpha.2 and json_serializable >=0.5.3 depends on analyzer ^0.32.0, flutter_driver from sdk is incompatible with json_serializable >=0.5.3.
So, because tangbole depends on both json_serializable ^0.5.8 and flutter_driver any from sdk, version solving failed.
pub get failed (1)
exit code 1
```

Tried to change version of `json_annotation`, `build_runner` and `json_serializable`, and not got a working group.

## Pubspec

```yaml
name: tangbole
description: A tumblr client app.

dependencies:
  cookie_jar: ^0.0.4
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  dio: ^0.0.14
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.1
  flutter_webview_plugin: ^0.1.6
  json_annotation: ^0.2.9
  logging: ^0.11.3+1
  meta: ^1.1.5
  path_provider: ^0.4.1
  uri: ^0.11.2
  redux: ^3.0.0
  redux_logging: ^0.3.0
  redux_persist: ^0.7.0-rc.2
  redux_persist_flutter: ^0.6.0-rc.1
  validate: ^1.6.0

dev_dependencies:
  build_runner: ^0.9.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: ^0.5.8
  mockito: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg

```
