### ISSUE TITLE
Invalid argument(s): Path must be absolute : dart:core

### ISSUE THREAD

**Issue by ollydixon** [dart-lang/json_serializable#542]
Doing the most basic json serializable stuff that's always worked on other projects.

I didn't change anything, simply came back to the project the day and encountered this error.

**My user**

```
import 'package:json_annotation/json_annotation.dart';

part 'user_v1.g.dart';

@JsonSerializable()
class UserV1 {
  String uid;

  /// Optional
  String profilePhotoUrl;
  String username;
  String createdISO;
  bool isBanned;
  bool isDeleted;
  bool isSubscribed;

  UserV1();

  factory UserV1.fromJson(Map<String, dynamic> json) => _$UserV1FromJson(json);
  Map<String, dynamic> toJson() => _$UserV1ToJson(this);
}
```

**build.yaml (root, I had to introduce this because it was trying to parse all the files in lib)**

```
targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false
          nullable: true
        generate_for:
          include:
          - lib/models/*
```

**My packages**
```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  simple_animations: ^1.3.3
  redux: ^3.0.0
  redux_persist: ^0.8.2
  flutter_storage: ^0.9.4
  path_provider: ^1.3.0
  shared_preferences: ^0.5.3+4
  flare_flutter: ^1.5.1
  json_annotation: ^3.0.0
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.11.1+3
  cloud_firestore: ^0.12.9+4
  cloud_functions: ^0.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.0
  json_serializable: ^3.2.2
```

**The error**
```
[INFO] Running build...
[SEVERE] json_serializable:json_serializable on lib/models/user_v1.dart:

Invalid argument(s): Path must be absolute : dart:core
[INFO] Running build completed, took 217ms
```

I tried deleting flutter, clearing the packages cache, build cache and much more. Nothing works.. at a dead end for hours..

**Comment by vferreirati** [comment]
I'm also having this problem. 
Downgrading to 3.0.0 (fixed) solved for me.

**Comment by ollydixon** [comment]
Yes downgrading worked, make sure you change your lock file for anyone else reading.

**Comment by cedx** [comment]
Same issue here. Fixed the error by using:

```yaml
json_annotation: ^3.0.0
json_serializable: 3.2.0 # Not using the caret symbol
```

**Comment by marcelgarus** [comment]
Getting the sam error using [`hive`](https://pub.dev/packages/hive) and [`hive_generator`](https://pub.dev/packages/hive_generator), so this issue is probably not library-specific.
Downgrading didn't help either, so I created an [issue in the dart-lang/build repo](https://github.com/dart-lang/build/issues/2457).

**Comment by cedx** [comment]
I also think that it's not an issue with this package but rather with the `analyzer` package. The error is not raised with this `pubspec.yaml`:

```yaml
analyzer: 0.38.2 # The error is raised if you use directly or transitively v0.38.3
json_annotation: ^3.0.0
json_serializable: ^3.2.2
```

Cf. dart-lang/sdk#38499
