### ISSUE TITLE
Json_serializable is not generating *.g.dart files

### ISSUE THREAD

**Issue by SwissCheese5** [dart-lang/json_serializable#636]
Given this class:
```dart
import 'dart:typed_data';

import 'package:meta/meta.dart';
import 'package:json_annotation/json_annotation.dart';

part 'entities.g.dart';

@JsonSerializable(nullable: false)
class User {
  final String uid;
  final String email;
  final String displayName;
  final String profilePicture;
  final String accountType;

  User(
      {@required this.uid,
      @required this.email,
      @required this.displayName,
      @required this.profilePicture,
      this.accountType});

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);

  Map<String, dynamic> toJson() => _$UserToJson(this);
}
```
![image](https://user-images.githubusercontent.com/7407478/80304384-0ffd0e80-87be-11ea-8446-bdc1f79e07eb.png)
(Image so you can see what my IDE is highlighting)

This is inside a dart file called `entities.dart` 
![image](https://user-images.githubusercontent.com/7407478/80304257-6ddd2680-87bd-11ea-88a1-acb5ab3c1c46.png)

This is my pubspec.yaml
```yaml
name: <...>
description: <...>

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^4.4.3
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  google_fonts: ^1.0.0
  json_annotation: ^3.0.1
  provider: ^4.0.5
  url_launcher: ^5.4.5
  image_picker: ^0.6.5+2
  image_picker_web: ^1.0.6
  string_validator: ^0.1.4
  intl_phone_number_input: ^0.3.0
  currency_pickers: ^1.0.6
  i18n_extension: ^1.3.5
  photo_view: ^0.9.2

dev_dependencies:
  build_runner: ^1.9.0
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
```

I am running the following command:
`flutter packages pub run build_runner build`

And this is the console output:

```
[INFO] Generating build script...
[INFO] Generating build script completed, took 384ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 75ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 741ms

[INFO] Running build...
[INFO] Running build completed, took 18ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 51ms

[INFO] Succeeded after 88ms with 0 outputs (0 actions)
```

I've tried many variations of the class, it simply wont generate anything.

I've tried a non-optional constructor, removing @required, changing imports, renaming the dart file, invalidating caches and restarting several times, renaming the class, etc...
